name: Changelog
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version tag to use instead of UNRELEASED'
        type: string
        required: false

      config_dir:
        description: 'git-chglog configuration directory'
        type: string
        required: false

      filename:
        description: 'Filename to write the changelog to'
        type: string
        required: false

      path:
        description: 'Optional path to follow for directory'
        default: ''
        type: string
        required: false

      tag_query:
        description: 'Optional tag query to use for changelog generation'
        default: ''
        type: string
        required: false

      commit_message:
        type: string
        description: "Commit message"
        required: false

permissions:
  contents: write

jobs:
  changelog:
    uses: maicol07/actions/.github/workflows/changelog.yml@main
    with:
      next_version: ${{ github.event.inputs.next_version }}
      config_dir: ${{ github.event.inputs.config_dir }}
      filename: ${{ github.event.inputs.filename }}
      path: ${{ github.event.inputs.path }}
      tag_query: ${{ github.event.inputs.tag_query }}
      commit_message: ${{ github.event.inputs.commit_message }}
