# Path: .github/workflows/release.yml
name: Release & Publish
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: '[CHANGELOG] Next version tag to use instead of UNRELEASED'
        type: string
        required: false

      config_dir:
        description: '[CHANGELOG] git-chglog configuration directory'
        type: string
        default: '.chglog'
        required: false

      filename:
        description: '[CHANGELOG] Filename to write the changelog to'
        type: string
        required: false
        default: CHANGELOG.md

      path:
        description: '[CHANGELOG] Optional path to follow for directory'
        default: ''
        type: string
        required: false

      tag_query:
        description: '[CHANGELOG] Optional tag query to use for changelog generation'
        default: ''
        type: string
        required: false

      commit_message:
        type: string
        description: "[CHANGELOG] Commit message"
        required: false

      version_type:
        type: choice
        description: "Version bump type"
        required: false
        options:
          - ''
          - patch
          - minor
          - major
          - rc
      release_channel:
        type: choice
        description: "Release channel"
        required: false
        options:
          - latest
          - next
          - beta
          - alpha

permissions:
  contents: write

jobs:
  release_publish:
    uses: maicol07/actions/.github/workflows/release_publish.yml@main
    with:
      version_type: ${{ github.event.inputs.version_type }}
      release_channel: ${{ github.event.inputs.release_channel }}
    secrets: inherit
